name: bongo_pay
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter_form_builder: ^9.1.1
  file_picker: ^6.1.1
  form_builder_validators: ^9.1.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  hooks_riverpod: ^2.4.10
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.11
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  local_auth: ^2.2.0
  country_picker: ^2.0.25
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^25.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: "assets/images/splash_screen.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 900
        
  
  
  
  
  
  
  
  
